# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6768c8ee8bcc15436a4881b9250a8860"
name = "Discount Bundle App"
application_url = "https://discount-bundle-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_orders,read_products,read_themes,write_discounts"

[access.admin]
embedded_app_direct_api_access = true
direct_api_mode = "online"

[auth]
redirect_urls = [
  "https://discount-bundle-production.up.railway.app/auth/callback"
]
