query CartInput($selectedCollectionIds: [ID!]) {
  cart {
    cost {
      subtotalAmount {
        amount
      }
    }
    buyerIdentity {
      customer {
        numberOfOrders
      }
    }
    lines {
      id
      quantity
      cost {
        amountPerQuantity {
          amount
        }
      }
      merchandise {
        ... on ProductVariant {
          id
          product {
            id
            inSelectedCollections: inAnyCollection(ids: $selectedCollectionIds)
          }
        }
      }
    }
  }
  discount {
    discountClasses
    bundleConfig: metafield(namespace: "$app:bundle-discount", key: "function-configuration") {
      value
    }
    volumeConfig: metafield(namespace: "$app:volume-discount", key: "function-configuration") {
      value
    }
    functionConfig: metafield( namespace:"$app:bundle-pack-3-for-999",key:"function-configuration"){
      value
    }
  }
}
